#!/bin/sh
# Log file for debugging
TZ='Asia/Shanghai'
LOG="/root/uci.log"
exec >>"$LOG" 2>&1
ts() { date -Iseconds; }
echo "==== $(ts) Starting script: $0 ===="
uci -q set samba4.@samba[0].disable_netbios='1'
uci -q set ddns-go.config.enabled='1'
#uci -q set dae.config.enabled='1'
uci -q set openlist.config.enabled='1'
uci -q set openlist.config.log_enable='0'
echo "set LAN gateway..."
LAN_IP='192.168.2.1'
#  LAN配置
uci set network.lan.ipaddr="$LAN_IP"
uci set network.lan.netmask='255.255.255.0'
echo "set RA DHCPv6..."
uci -q del dhcp.lan.ra_slaac
uci -q del dhcp.lan.dhcpv6
uci set dhcp.lan.ra='server'
uci set dhcp.lan.force='1'

uci commit
exit 0